# Generated by Django 5.1.3 on 2024-12-27 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ovqat nomi')),
                ('about', models.TextField(blank=True, null=True, verbose_name='ovqat haqida')),
                ('photo', models.ImageField(upload_to='media/photos/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oqtepa.category', verbose_name='ovqat turi')),
            ],
            options={
                'verbose_name': 'Ovqat',
                'verbose_name_plural': 'Ovqatlar',
            },
        ),
    ]
